[package]
# Package Information
name = oposs_apc_wireless
title = OPOSS APC Wireless Sensors
author = Tobias Oetiker <tobi@oetiker.ch>
description = This check monitors APC wireless temperature and humidity sensors via SNMP.

    It tracks temperature and humidity readings from APC EM/NetBotz
    wireless sensor pods connected to APC UPS systems.

# CheckMK Compatibility
version.min_required = 2.3.0p1
version.packaged = 2.3.0p34

# Optional
download_url = https://github.com/oposs/cmk-oposs_apc_wireless
version.usable_until =

# Build Options
validate_python = true
